name: Ping from Remote Call
on: [workflow_dispatch]
jobs:
  Echo-to-Console:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello! üê≠"
      - name: Check secret length
        run: |
          echo "URL length: ${#${{ secrets.DISCORD_WEBHOOK }}}"
      - name: Echo to Discord
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H 'Content-Type: application/json' \
          -d '{"content": "Hello, Discord!", "username": "HiBot"}'
      - name: Say bye
        run: echo "Bye now~ üê≠"
